import turtle

t=turtle.Turtle()
s=turtle.Screen()
t.hideturtle()
s.bgcolor("black")
t.color("#eeeeee")
t.begin_fill()
t.circle(100)
t.end_fill()

t.left(90)
t.forward(75)
t.right(90)
t.backward(60)
t.begin_fill()

t.color("#50d890")
def logo(length,radius,angle):
    for i in range(2):
         t.forward(length)
         t.circle(radius,angle)

t.fd(120)
t.left(90)
t.circle(60,180)
t.end_fill()
t.circle(60,-60)
t.right(90)
t.begin_fill()
logo(20,3,180)
t.end_fill()
t.left(90)
t.circle(60,-60)
t.right(90)
t.begin_fill()
logo(20,3,180)
t.end_fill()
t.left(90)
t.circle(60,-60)
t.left(90)
t.fd(30)
t.rt(90)

t.fd(20)
t.color("#eeeeee")
t.dot(10)
t.penup()
t.lt(90)
t.fd(60)
t.dot(10)
turtle.exitonclick()
