import turtle
t=turtle.Turtle()
s=turtle.Screen()
z=turtle.Turtle()
t.hideturtle()
z.hideturtle()
p=turtle.Turtle()
p.hideturtle()
p.hideturtle()
p.speed(10)
t.speed(10)
z.speed(10)
turtle.title("DESKTOP SETUP")
#s.bgcolor("light salmon")
s.bgcolor("#0f3460")
def rect(length,breadth,radius,a):
    for i in range(2):
        a.forward(length)
        a.circle(radius,90)
        a.forward(breadth)
        a.circle(radius,90)


def stick(length,radius,A):
    for i in range(2):
        A.forward(length)
        A.circle(radius,180)


#mob

p.penup()
p.backward(600)
p.left(90)
p.backward(190)
p.right(90)
p.pendown()
p.fillcolor("#e8e8e8")
p.begin_fill()
rect(200,380,20,p)
p.end_fill()
p.circle(20,-90)
p.backward(24)
p.left(90)
p.penup()
p.fd(10)
p.pendown()
p.fillcolor("#132743")
p.begin_fill()
rect(220,330,5,p)
p.end_fill()
p.penup()
p.bk(10)
p.right(90)
p.fd(19)
p.circle(20,90)
p.fd(100)
p.penup()
p.begin_fill()
p.circle(15)
p.end_fill()

#############################



t.fillcolor("black")
t.begin_fill()
rect(200,103,10,t)
t.end_fill()
t.left(90)
t.penup()
t.forward(10)
t.right(90)
t.forward(10)
t.pendown()
t.fillcolor("LAVENDER")
t.begin_fill()
rect(180,83,10,t)
t.end_fill()
t.penup()
t.left(90)
t.forward(77)
t.right(90)
t.forward(5)
t.pendown()
t.fillcolor("STEELBLUE")
t.begin_fill()
stick(80,5,t)
t.end_fill()
#####2nd
t.penup()
t.right(90)
t.forward(30)
t.left(90)
t.pendown()
t.fillcolor("ANTIQUEWHITE")
t.begin_fill()
stick(40,5,t)
t.end_fill()
###3rd
t.penup()
t.right(90)
t.forward(30)
t.left(90)
t.pendown()
t.fillcolor("LIGHTGRAY")
t.begin_fill()
stick(20,5,t)
t.end_fill()

###########################################################
z.color("white")
z.penup()
z.forward(85)
z.pendown()
z.begin_fill()
z.color("light slate gray")
rect(30,-40,0,z)
z.end_fill()
z.left(90)
z.forward(-40)
z.right(90)
z.backward(20)
z.begin_fill()
z.color("DARKSLATEGRAY")
stick(70,-5,z)
z.end_fill()
z.left(180)
z.circle(5,180)
z.color("black")
z.backward(250)
z.begin_fill()
stick(400,-7,z)
z.end_fill()
############################
z.forward(40)
z.begin_fill()
rect(50,110,10,z)
z.end_fill()
z.forward(6)
z.begin_fill()
z.color("ALICEBLUE")
rect(38,104,10,z)
z.end_fill()
z.color("black")
z.left(180)
z.forward(46)
z.circle(7,180)
z.forward(40)
z.right(110)

z.begin_fill()
stick(150,-7,z)
z.end_fill()

z.left(110)
z.forward(325)
z.left(290)
z.begin_fill()
stick(148,-7,z)
z.end_fill()
turtle.exitonclick()
