#gmail logo
import turtle
t=turtle.Turtle()
m=turtle.Turtle()
#t.speed(100)
#m.speed(100)
t.hideturtle()
m.hideturtle()
s=turtle.Screen()
s.bgcolor("#132743")
t.color("white")
t.begin_fill()
t.circle(100)
t.end_fill()
m.circle(100,340)
m.color("red")
m.left(110)
def squire(length,radius,breadth):
    for i in range(2):
        m.forward(length)
        m.circle(radius,90)
        m.forward(breadth)
        m.circle(radius,90)
m.penup()
m.forward(45)
m.right(90)
m.backward(10)
m.pendown()
m.color("gainsboro")
m.begin_fill()
squire(81,20,50)
m.end_fill()

m.left(90)
def mega(length,radius):
    
    m.forward(length)
    m.circle(radius,90)
    m.right(30)

m.left(90)

m.circle(-20,90)
m.color("red")
m.begin_fill()
mega(54,-15)
m.forward(52)
m.left(60)
m.forward(54)
m.right(30)

m.circle(-15,90)
m.forward(55)
m.circle(-6,180)
mega(55,0)
m.left(60)
m.forward(55)
m.right(60)
mega(58,0)
m.left(60)
m.forward(55)
m.circle(-6,180)
m.end_fill()
m.hideturtle()
t.hideturtle()
turtle.exitonclick()
