import turtle
t=turtle.Turtle()
t.hideturtle()

capplist=["#0f4c75","#bbe1fa","#ade498","#ebecf1"]
s=turtle.Screen()
s.bgcolor("#ebecf1")
turtle.title('ONEPLUS NORD')
t.penup()
t.right(90)
t.fd(150)
t.left(90)
t.pendown()
t.color("#251f44")
def screen(length,breadth,rad):
    for i in range(2):
        t.fd(breadth)
        t.circle(rad,90)
        t.fd(length)
        t.circle(rad,90)

t.begin_fill()
screen(450,220,20)
t.end_fill()
t.left(90)
t.fd(10)
t.right(90)
t.fd(5)
t.color("black")
t.pensize(2)
t.begin_fill()
t.fillcolor("#ffeadb")
screen(435,210,20)
t.end_fill()
t.penup()
t.left(90)
t.forward(455)
t.right(90)
t.fd(5)
t.pensize(18)
t.pendown()
t.fd(29)
t.backward(29)
t.penup()
t.right(90)
t.fd(55)
t.left(90)
t.pendown()
t.color("#d3dbff")
t.fd(200)
t.backward(200)
t.pensize(2)
t.color("black")
t.left(90)
t.penup()
t.fd(6)
t.rt(90)
t.fd(9)
t.rt(180)
t.pendown()
##g
t.circle(6,230)
t.left(30)
t.fd(3)
t.left(100)
t.fd(4)
#####
t.penup()
t.left(90)
t.fd(380)
t.left(90)
t.pensize(2)
t.pendown()
for i in range(4):
    if i==3:
        t.pensize(4)
    
    t.begin_fill()
    t.fillcolor(capplist[i])
    t.circle(15)
    t.end_fill()
    t.penup()
    t.fd(60)
    t.pendown()
t.penup()
t.backward(155)
t.pensize(1)
t.left(90)

t.fd(80)
t.pendown()
t.right(30)
t.fd(5)
t.rt(120)
t.fd(6)
