#python logo
import turtle
t=turtle.Turtle()
p=turtle.Turtle()
turtle.title("PYTHON LOGO")
s=turtle.Screen()
t.hideturtle()
p.hideturtle()

#s.bgcolor('#16213e')
s.bgcolor("black")
t.color('royal blue')
t.left(180)
#####
def python(z):
    z.forward(25)
    z.circle(-20,70)
    z.circle(-80,45)
    z.circle(-20,65)
    z.fd(85)
    z.circle(5,180)
    z.fd(55)
    z.right(90)
    z.fd(25)
    z.circle(-20,90)
    z.fd(65)
    z.circle(-20,90)
    z.fd(60)
    z.circle(-20,90)
    z.fd(70)
    z.circle(20,90)
    z.fd(20)
def eyes(e):
    e.penup()
    e.backward(115)
    e.left(90)
    e.fd(23)
    e.dot(10,'white')
    e.hideturtle()

t.begin_fill()
python(t)
t.end_fill()
p.color('Gold')
p.penup()
p.forward(112)
p.left(90)
p.fd(81)
p.right(90)
p.pendown()
p.begin_fill()
python(p)
p.end_fill()
###
eyes(p)
eyes(t)
turtle.exitonclick()
