/* create a class called bankClient, 3 private attribute id(autogenerated)
name, balance(add, get, subtract if possibe), constructor to initialize hte 
name, a method called bank data(noOfClient, Bankbalance) */

class BankClient{
  static int id = 0;
  int? custId=id+1;
  String? name;
  double balance=0;
  static double mainBalance= 0;
  
  BankClient(String name){
    this.name = name;
    id = id + 1;
  }
  
  void addBalance(double bal){
      balance = bal;
      mainBalance = mainBalance + balance;
  }
  
  void bankData(){
    print("\nClient Id: ${id}");
    print("Balance: ${mainBalance}");
  }
  
  void details(){
    print("name: ${name} balance: ${balance}  id: ${custId}");
  }
}

void main(){
  BankClient a = new BankClient("name1");
  BankClient b = new BankClient("name2");
  
  a.addBalance(1200);
  b.addBalance(1500);
  
  a.details();
  b.details();
  
  a.bankData();
}