# Generated by Django 3.2.5 on 2021-07-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShorternedURL',
            new_name='ShortenedURL',
        ),
    ]
